#!/bin/bash

SCRIPT_DIR=$(cd $(dirname $0) && pwd)

TARGET_TIMEZONE="Asia/Tokyo"
if [ -e ${SCRIPT_DIR}/chtimezone ];
  ${SCRIPT_DIR}/chtimezone ${TARGET_TIMEZONE}
else
  curl --silent https://raw.githubusercontent.com/kotazuck/scripts/master/ubuntu/chtimezone | sh -- ${TARGET_TIMEZONE}
fi

